project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - projects/leverage_effect.qmd

website:
  title: "Actuarial Projects Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/financial_mathematics.qmd
        text: Financial Mathematics
    right:
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/ma-latala
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true