project:
  type: website
  output-dir: docs

website:
  title: "Actuarial Projects Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/leverage_effect.qmd
        text: Leverage Effect
  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true